extends Node

const PHYSICS_TICKS_PER_SECOND := 60
const WORLD_SIZE := Vector2(3200.0, 2400.0)
const CAMERA_LOOKAHEAD := 80.0
const CAMERA_LERP := 0.08
const CAMERA_BOSS_TELEGRAPH_TICKS := 90

const GRID_CELL_SIZE := 80.0
const ACTIVE_ENEMY_CAP := 80
const PLAYER_BULLET_CAP := 300
const ENEMY_BULLET_CAP := 500
const DAMAGE_NUMBER_CAP := 70

const PLAYER_HP := 100.0
const PLAYER_RADIUS := 11.0
const PLAYER_SPEED := 3.3
const PLAYER_DAMAGE := 10.0
const PLAYER_FIRE_RATE_TICKS := 11
const PLAYER_PROJECTILE_SPEED := 9.5
const PLAYER_PROJECTILE_LIFE_TICKS := 80
const PLAYER_DASH_COOLDOWN_TICKS := 90
const PLAYER_DASH_DURATION_TICKS := 9
const PLAYER_DASH_SPEED_PER_TICK := 13.0
const PLAYER_DASH_IFRAME_TICKS := 14
const PLAYER_HURT_IFRAME_TICKS := 40
const PLAYER_BULLET_HURT_IFRAME_TICKS := 35
const PLAYER_KNOCKBACK := 22.0
const LAVA_DAMAGE := 4.0
const LAVA_DAMAGE_INTERVAL_TICKS := 30

const SHAKE_DECAY := 0.85
const SHAKE_SHOT := 1.0
const SHAKE_KILL := 3.5
const SHAKE_ELITE_KILL := 7.0
const SHAKE_PLAYER_HURT := 10.0
const SHAKE_ENEMY_BULLET_HURT := 8.0
const HITSTOP_PLAYER_HURT_TICKS := 4
const HITSTOP_BOSS_KILL_TICKS := 8

const SPAWN_INITIAL_DELAY_TICKS := 30
const BOSS_TELEGRAPH_TICKS := 90
const SPAWN_OFFSCREEN_MIN := 60.0
const SPAWN_OFFSCREEN_MAX := 140.0
const SPAWN_INTERVAL_MIN_TICKS := 6
const SPAWN_INTERVAL_BASE_TICKS := 40
const SPAWN_INTERVAL_WAVE_REDUCTION := 2

const ENEMY_HP_SCALE_LINEAR := 0.32
const ENEMY_HP_SCALE_EXP := 1.6
const ENEMY_HP_SCALE_EXP_FACTOR := 0.02
const ELITE_BASE_CHANCE := 0.03
const ELITE_WAVE_CHANCE := 0.006
const ELITE_MAX_CHANCE := 0.22
const ELITE_HP_MULT := 2.6
const ELITE_SPEED_MULT := 1.12
const ELITE_DAMAGE_MULT := 1.3
const ELITE_RADIUS_MULT := 1.18

const WAVE_BASE_COUNT := 8
const WAVE_COUNT_PER_WAVE := 2.6
const WAVE_COUNT_CAP := 110
const WAVE_SPITTER_ROLL := 0.20
const WAVE_BRUTE_ROLL := 0.34
const WAVE_SPLITTER_ROLL := 0.46
const WAVE_HOUND_ROLL := 0.58
const COMBO_DECAY_TICKS := 180
const LOD_SEPARATION_VIEWPORT_MULT := 1.5
const THREAT_CHEVRON_MAX := 12

const SPLITTER_CHILD_SPACING := 18.0
const HOUND_TRIGGER_RANGE := 340.0
const HOUND_WINDUP_TICKS := 26
const HOUND_CHARGE_TICKS := 22
const HOUND_CHARGE_SPEED := 9.0
const HOUND_RESET_MIN_TICKS := 70
const HOUND_RESET_MAX_TICKS := 110

const BOSS_RING_BULLET_SPEED := 3.0
const BOSS_FAN_BULLET_SPEED := 4.6
const BOSS_FAN_SPREAD_RADIANS := 0.16
const BOSS_BULLET_RADIUS := 6.0
const BOSS_BULLET_DAMAGE := 14.0
const BOSS_RING_BULLET_LIFE_TICKS := 240
const BOSS_FAN_BULLET_LIFE_TICKS := 220
const BOSS_CHARGE_WINDUP_TICKS := 34
const BOSS_CHARGE_TICKS := 30
const BOSS_CHARGE_SPEED := 7.0

const DROP_HEART_HEAL := 12.0
const DROP_EMBER_SCORE := 60
const DROP_PICKUP_RADIUS := 20.0
const DROP_MAGNET_RADIUS := 110.0
const DROP_MAGNET_PULL := 7.0
const HEART_DROP_CHANCE := 0.045
const EMBER_DROP_CHANCE := 0.22
const ELITE_HEART_DROP_CHANCE := 0.45
const CHEST_RADIUS := 16.0

const OBJECTIVE_MARKER_RADIUS := 42.0
const OBJECTIVE_VEIN_ERUPT_COUNT := 6
const OBJECTIVE_BRAZIER_BONUS_CHOICES := 1
const OBJECTIVE_BOUNTY_DESPAWN_TICKS := 2700
const ANVIL_DEFENSE_START_HP := 300.0
const ANVIL_DEFENSE_HP_PER_WAVE := 40.0
const ANVIL_DEFENSE_BLESSING_HP := 30.0
const ANVIL_THREAT_RADIUS := 520.0

const BURN_TICK_INTERVAL := 20
const BURN_DAMAGE_FACTOR := 0.18
const DETONATING_BRAND_RADIUS := 130.0
const DETONATING_BRAND_DAMAGE_FACTOR := 1.35
const BLAST_FURNACE_RADIUS := 170.0
const BLAST_FURNACE_DAMAGE_FACTOR := 2.2
const BLAST_FURNACE_DASH_REFUND := 0.30
const OVERCLOCK_STILL_TICKS := 60
const OVERCLOCK_FIRE_RATE_MULT := 0.60
const METEOR_RADIUS := 115.0
const RAILSPIKE_WIDTH := 34.0

var rng := RandomNumberGenerator.new()
var run_seed := 0
var screen_shake_scale := 1.0

func _ready() -> void:
	Engine.physics_ticks_per_second = PHYSICS_TICKS_PER_SECOND
	set_run_seed(0xE4BEF411)

func set_run_seed(seed_value: int) -> void:
	run_seed = seed_value
	rng.seed = seed_value

func randf_range(min_value: float, max_value: float) -> float:
	return rng.randf_range(min_value, max_value)

func randi_range(min_value: int, max_value: int) -> int:
	return rng.randi_range(min_value, max_value)

func enemy_hp_scale(wave: int) -> float:
	return 1.0 + wave * ENEMY_HP_SCALE_LINEAR + pow(float(wave), ENEMY_HP_SCALE_EXP) * ENEMY_HP_SCALE_EXP_FACTOR

func elite_chance(wave: int) -> float:
	return min(ELITE_BASE_CHANCE + wave * ELITE_WAVE_CHANCE, ELITE_MAX_CHANCE)

func spawn_interval(wave: int) -> int:
	return max(SPAWN_INTERVAL_MIN_TICKS, SPAWN_INTERVAL_BASE_TICKS - wave * SPAWN_INTERVAL_WAVE_REDUCTION)
